### ISSUE TITLE
Enable `Promise.all` to take an object.

### ISSUE THREAD

**Issue by PierreGaudichon** [then/promise#101]
Would it be possible to make `Promise.All` to take an object of promises and return a new one. 

Here is almost the same example as in the doc.

```javascript
Promise
	.all({
		a: Promise.resolve('a'),
		b: 'b',
		c: Promise.resolve('c')
	})
	.then(function (res) {
		assert(res.a === 'a')
		assert(res.b === 'b')
		assert(res.c === 'c')
	})
```

**Comment by ForbesLindesay** [comment]
This is a relatively rare use case that could easily be handled with a separate `then-all-object` module.  It does not belong as part of core, and certainly not in the same method as `promise.all`.

It is, however, a very nice idea for a bit of functionality.  If you would like to write it, I would be happy to add it to this org, and perhaps even link to it from promisejs.org.

**Comment by nathan7** [comment]
https://www.npmjs.com/package/when-every-key fills this void already for me, agree that this shouldn't be in core (object iteration is full of bikesheds — see ES6 object spreads)
