### ISSUE TITLE
Cannot bundle module 'promise'

### ISSUE THREAD

**Issue by miherlosev** [then/promise#104]
See steps to reproduce and example in https://github.com/medikoo/modules-webmake/issues/53/#issue-100993250

Can promise be bundled by using https://github.com/medikoo/modules-webmake?

**Comment by nathan7** [comment]
That's a bug in webmake not supporting the `browser` field in `package.json`.
https://github.com/kriskowal/asap/blob/d7359b771fb3ff41f8bfcbb1fa00ade7126fc622/package.json#L19-L23
Webpack and Browserify support it just fine.
