### ISSUE TITLE
Immediate reject execution

### ISSUE THREAD

**Issue by vitaly-t** [then/promise#108]
Trying to understand why sometimes calling `reject()` suddenly causes immediate execution of the reject chain.

Example:

```javascript
function Test() {
    return new Promise(function (resolve, reject) {
        console.log("step-1");
        reject();
        console.log("step-2");
    });
}

Test()
    .then(function () {
    }, function () {
        console.log("step-3");
    });
```
This is always expected to produce the following output:
```
step-1
step-2
step-3
```
However, when under heavy load and with lots of things running in parallel I suddenly get the following logged:
```
step-1
step-3
step-2
```
which indicates that under some special circumstances that are hard to reproduce, calling `reject()` results in immediate execution of the reject chain.

How is this even possible?

**Comment by ForbesLindesay** [comment]
I don't know what could cause this.  If you can provide a failing test case (e.g. as a pull request) we can try and investigate this.  It shouldn't be possible.

**Comment by vitaly-t** [comment]
As I stated above, this is very difficult to reproduce, but over time the anomaly appears to be consistent.

I'm not sure I will be able to create such a failing test. The only thing seems feasible right now is to analyse implementation of the reject call to see if there is any scenario when a direct execution may occur. Also, I will try to switch to a different promise library to see if that makes a difference.

**Comment by ForbesLindesay** [comment]
It always goes through `asap`, so the only thing I can see that would cause this would be a bug in asap.  There were some bugs in some older versions of asap, so check your up to date.

**Comment by vitaly-t** [comment]
I've been using the very latest version of `Promise`, which presumes an up-to-date version of the `asap` also. This very well may be that `asap` faults under a heavy load and executes a reject out of order.

**Comment by vitaly-t** [comment]
Closing it, as I cannot prove that this is the case. Maybe my code is broken elsewhere.
