### ISSUE TITLE
Requires "process" global

### ISSUE THREAD

**Issue by moll** [then/promise#110]
Hey,

I'm not sure whose responsibility this is, but Promise's use of ASAP ends up depending on a `process` global which, I'd say, it shouldn't, and which doesn't exist in browsers. ASAP's raw.js require on https://github.com/then/promise/blob/8a42572e23669b685b659d1fa56532c7b05fb8d7/src/core.js#L3 ends up at https://github.com/kriskowal/asap/blob/d7359b771fb3ff41f8bfcbb1fa00ade7126fc622/raw.js#L76.

Cheers

**Comment by ForbesLindesay** [comment]
This will be resolved by https://github.com/kriskowal/asap/pull/63 as it is a bug with asap.
