### ISSUE TITLE
Support for node js domains

### ISSUE THREAD

**Issue by mkeshavgarg** [then/promise#113]
promise.js breaks node js domains.

    //express.js
    domain = require('domain');
    app.use(function(req, res, next) {
        var reqDomain = domain.create();
        
        reqDomain.run( function (req, res, next) {
            console.log(process.domain);     //defined
            
            Promise.all([promise1, promise2]).then(function() {
                console.log(process.domain);    //  ERROR: process.domain is undefined
            }) 
        })
    })

**Comment by ForbesLindesay** [comment]
If you want to use domains you need to do `require('promise/domains')` instead of `require('promise')`.  You shouldn't really need domains when using promises though, since promises handle error bubbling properly anyway.

**Comment by nathan7** [comment]
It's also worth noting that domains are deprecated (https://nodejs.org/api/domain.html#domain_domain)

**Comment by ForbesLindesay** [comment]
Yes, that too.  I never understood why anyone thought they were a good idea.  I guess it was just people who didn't understand promises.

**Comment by mkeshavgarg** [comment]
I am not using domains for error bubbling.

I am aware that domains will soon be fully deprecated and will be replaced by some other API but for now my use case needs node.js domains.

In java there is a concept called thread local which helps to define variables in the context of that thread but in node we do not have anything like that but domains.
I found domains very useful in providing context for particular set of operations and mimicking thread local storage.

Use Case: 
1. I need to access the request context in mongoose model pre/post hooks
2. I need to access the request context in request handlers

Solution: Create domain in the context of request

    app.use(function(req, res, next) {
        var reqDomain = domain.create();
        reqDomain.run(next);
    });

Now with the use of process.domain, I will be able to access 'data' bound to above created domain anywhere
Eg:

    var d = process.domain
    d.obj = {};


Similar use case has been discussed here:
https://github.com/nodejs/node-v0.x-archive/issues/3733

**Comment by ForbesLindesay** [comment]
You can easily implement this yourself on top of promises via something like:

```js
var Promise = require('promise');
var originalThen = Promise.prototype.then;
Promise.prototype.then = function (cb, eb) {
  if (typeof cb === 'function') {
    // bind cb to the current domain
  }
  if (typeof eb === 'function') {
    // bind eb to the current domain
  }
  return originalThen.call(this, cb, eb);
};
```

We're not going to provide it by default because it represents a huge performance hit.
