### ISSUE TITLE
Many arguments in resolve and reject

### ISSUE THREAD

**Issue by LestaD** [then/promise#117]
```js
import Promise from 'promise';

let test = new Promise((resolve, reject) => {
  (new Promise((res, rej) => {
    setTimeout(() => res({ foo: 1, bar: 2 }, 300));
  }))
  .then((response) => resolve(response.foo, response.bar));
});

test.then((arg1, arg2) => {
  console.log(arg1, arg2);
});
```

But in console i see only first argument, second is undefined

**Comment by LestaD** [comment]
```js
console.log(resolve.toString());
```

![image](https://cloud.githubusercontent.com/assets/5620073/11933101/c9d702b8-a80a-11e5-942e-6182b6be4d7a.png)

Maybe change `resolve` to:

```js
function () {
  if (done) return;
  done = true;
  resolve(promise, [].slice.call(arguments));
}
```

or something else, for many arguments support?

**Comment by ForbesLindesay** [comment]
Promises model the results of function calls.  Functions can only return a single value so promises can only resolve to a single value.  For multiple, values, use an array:

```js
import Promise from 'promise';

let test = new Promise((resolve, reject) => {
  (new Promise((res, rej) => {
    setTimeout(() => res({ foo: 1, bar: 2 }), 300);
  }))
  .then((response) => resolve([response.foo, response.bar]));
});

test.then(([arg1, arg2]) => {
  console.log(arg1, arg2);
});
```

**Comment by ForbesLindesay** [comment]
Feel free to continue discussion if you have further questions, but since this is part of the core Promises/A+ and ES2015 spec, it's not going to change.
