### ISSUE TITLE
Question: write way to use catch

### ISSUE THREAD

**Issue by AliMD** [then/promise#124]
I'm sorry for writing my question here. i'm not sure its my mistake or promise issue.

When i use catch i don`t see any javascript errors in my codes anymore!
For example look at this code
```javascript
somePromissyFunction()
.then(() => {
  someBuggyFunction();
})
.catch(() => {
  console.log('You always see me! but there is no error happened in somePromissyFunction!');
})
;

function someBuggyFunction (){
  var a={};
  // make some error
  var b=a.undefinedname.bug;
  // you dont see any error becouse this founction call from some promissy function
}
```

Do you think its write way for make promise catch ? or i don't understand the benefited ?
I think developers conflicted to find the bugs and we prefer to see usual js errors and handle it my self.
Thank you in advance.

**Comment by AliMD** [comment]
By the way for skip this issue we must use setTimeout for call `someBuggyFunction`
```javascript
.then(() => {
  setTimeout(()=>{
    someBuggyFunction();
  })
})
```

Any other solution ?

**Comment by khalilof** [comment]
the catch and then belong to the _somePromissyFunction_ and so when this function returns a success (resloved case ) the code wrapped with **then ** will be executed , and if it returns a failure (rejected ) then the code wrapped with **catch** will be executed ,
the catch here has nothing to do with JavaScript error handling or exceptions, it's the pre-defined failur case of your promise 

and Yes, this is not the correct place for this question, you could put it in stackoverflow

cheers

**Comment by AliMD** [comment]
I w
