### ISSUE TITLE
stuck with Promise.all

### ISSUE THREAD

**Issue by nurulnabi** [then/promise#134]
Promise.all causes to reject every promise if anyone is rejected. Suppose most of the promises got settled but only few of them (let one of them) got rejected. Isn't it awkward to reject all the settled promises just because one got rejected? Again, if more than one promise got rejected there is no way to know them. It should work like if any promise got resolved then go to corresponding .then else .catch for all.This way we can know which promise got resolved which got rejecterd.

**Comment by edef1c** [comment]
This API is standardised as part of JavaScript - we're just implementing it.
