### ISSUE TITLE
'get' is not defined  no-undef

### ISSUE THREAD

**Issue by newbiedev1987** [then/promise#136]
Steps to reproduce (I am using React):

- `yarn add promise`, which adds `"promise": "^8.0.0"` to package.json
- Add `import Promise from 'promise';` to the top of the file
- Add: 
```
componentDidMount() {
    var promise = new Promise(function (resolve, reject) {
      get('http://www.google.com', function (err, res) {
        if (err) reject(err);
        else resolve(res);
      });
    });
  }
```
- Response: 
```
Line 19:  'get' is not defined  no-undef
Search for the keywords to learn more about each error.`
```

What am I doing wrong??

**Comment by ForbesLindesay** [comment]
This problem is not caused by the promise library.  Please ask questions like this on https://stackoverflow.com/
