### ISSUE TITLE
Please don't silently catch errors

### ISSUE THREAD

**Issue by jankeromnes** [then/promise#137]
This module has a few `try/catch` blocks that catch errors without logging them. This can make debugging really hard, especially when you're not using the `promise` module yourself (This is currently hitting us in the [janitor](https://github.com/JanitorTechnology/janitor) project, which uses the [email-login](https://github.com/espadrine/email-login) module, which itself uses the `then/promise`. Many errors in Janitor or its modules are just caught by `then/promise`, leaving us hanging without any useful error message).

The offending `tr/catch` blocks are [here](https://github.com/then/promise/blob/1272f80b7f88feb58e09295c43d822a4dcf9609f/src/core.js#L29), [here](https://github.com/then/promise/blob/1272f80b7f88feb58e09295c43d822a4dcf9609f/src/core.js#L38), and [here](https://github.com/then/promise/blob/1272f80b7f88feb58e09295c43d822a4dcf9609f/src/core.js#L46).

When I hack this module to add `console.error(ex)` to all these silent catches, I finally see errors like this one for example:

```
Error: Template error: macro "=" didn't work.
Parameters: title,in,nosuchparser
Literal: $_parsers $_parsedtext0 $_parsernames1 $_parserparams2 $_i3 $_scopestr machines projects version title user scripts $_scope $_write $_end
Message: Template error: parser nosuchparser is missing.
    at evalmachine.<anonymous>:74:9
    at ContextifyScript.Script.runInContext (vm.js:32:29)
    at ContextifyScript.Script.runInNewContext (vm.js:38:15)
    at runner (/home/ubuntu/workspace/node_modules/@jankeromnes/camp/node_modules/fleau/fleau.js:247:12)
    at /home/ubuntu/workspace/node_modules/@jankeromnes/camp/lib/camp.js:88:16
    at Array.map (native)
    at ServerResponse.res.template (/home/ubuntu/workspace/node_modules/@jankeromnes/camp/lib/camp.js:84:37)
    at Object.exports.landingPage (/home/ubuntu/workspace/lib/routes.js:105:12)
    at app.route (/home/ubuntu/workspace/app.js:97:12)
    at gotQueries (/home/ubuntu/workspace/node_modules/@jankeromnes/camp/lib/camp.js:887:7)
```

(Which has nothing to do with `then/promise`, but is in fact a legitimate error in `janitor` template files parsed by the `fleau` module... which we never see logged on our end, unless we hack your `promise/src/core.js`).

Here is an example stack trace of an error that is silently caught (but we still log the stack trace later because we have another way of noticing that something went wrong so we log a `new Error()` which has this stack trace):

```
[2017-07-06T11:55:43.839Z] Error: Something went wrong
    at login.confirmEmail (/home/janx/janitor/lib/sessions.js:100:16)
    at /home/janx/janitor/node_modules/email-login/src/api.js:194:13
    at /home/janx/janitor/node_modules/email-login/src/registry.js:67:18
    at tryCallOne (/home/janx/janitor/node_modules/fsos/node_modules/promise/lib/core.js:37:12)
    at /home/janx/janitor/node_modules/fsos/node_modules/promise/lib/core.js:103:15
    at flush (/home/janx/janitor/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

The line `node_modules/fsos/node_modules/promise/lib/core.js:37:12` is where our valid exception gets vacuumed and never logged (so we don't know what the actual error is).

Could you please log all the exceptions caught here with a `console.error(ex)`?

Or maybe the silent exceptions are a symptom that some `janitor` direct dependencies like `fleau`, `email-login` or `fsos` use `then/promise` in a wrong way?

**Comment by ForbesLindesay** [comment]
See https://github.com/then/promise#unhandled-rejections

**Comment by ForbesLindesay** [comment]
In general, the promise returned by these modules should be "rejected" and it's up to you to handle that rejection.  If you end your promise chains with `.done`, errors will always be surfaced properly.

**Comment by jankeromnes** [comment]
So one of my node dependencies uses the `promise` library (https://github.com/espadrine/fsos), but seems to not handle at least one rejection, so Travis fails for my pull request https://github.com/JanitorTechnology/janitor/pull/102:

```
Error: We could not prove email ownership
    at /home/travis/build/JanitorTechnology/janitor/node_modules/email-login/src/api.js:136:30
    at /home/travis/build/JanitorTechnology/janitor/node_modules/email-login/src/registry.js:165:40
    at /home/travis/build/JanitorTechnology/janitor/node_modules/email-login/src/registry.js:108:16
    at tryCallOne (/home/travis/build/JanitorTechnology/janitor/node_modules/fsos/node_modules/promise/lib/core.js:37:12)
    at /home/travis/build/JanitorTechnology/janitor/node_modules/fsos/node_modules/promise/lib/core.js:103:15
    at flush (/home/travis/build/JanitorTechnology/janitor/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

Which simply means there was an error, but it's been trapped by `promise`'s silent catch. ☹️ And since it's on Travis, I can't hack `/node_modules/fsos/node_modules/promise/lib/core.js:37` to log the actual error...

Worth noting, Node.js's native Promises throw any unhandled rejections instead of silently sweeping it under the rug. I think that's a much saner behavior. Would you be open to doing something similar in your `promise` module?

**Comment by jankeromnes** [comment]
I tried adding `require('promise/lib/rejection-tracking').enable({ allRejections: true });` at the top of my `tests.js` file, but it didn't work:

- Enable rejection tracking for all rejections: https://github.com/JanitorTechnology/janitor/pull/102/files#diff-2a8a5fef3397df87ab538f028a5c6b50R6
- The mystery error is still silently swallowed by `promise`: https://travis-ci.org/JanitorTechnology/janitor/builds/251991510#L736

**Comment by ForbesLindesay** [comment]
That's probably because these are **not** silently being swallowed by `promise`. Instead they are being **handled** by some other code.  If you have something like:

```js
Promise.reject(new Error('whatever')).catch(err => {
  // handle the err
});
```

That is not treated as an unhandled rejection by Promise (or indeed by node.js's native Promises).  This is similar to how if you write `try {throw new Error('whatever'); } catch (ex) {}` no tools will show you that error by default.
