### ISSUE TITLE
Can't pass promise into a promise

### ISSUE THREAD

**Issue by hakunin** [then/promise#139]
```
var promise1 = new Promise((resolve, reject) => { resolve() });
var promise2 = new Promise((resolve, reject) => { resolve(promise1) }).then((result) => {
  console.log('result was', result);
});

var promise1 = new Promise((resolve, reject) => { resolve() });
var promise2 = new Promise((resolve, reject) => { resolve({promise: promise1}) }).then((result) => {
  console.log('result was', result);
});
```

result
```
result was {promise: Promise}
result was undefined
```

fiddle:
https://jsfiddle.net/1028a3vp/1/

Update: looks like the native promise produces the same result :(

There is some extra behavior when a promise is passed: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve

**Comment by ForbesLindesay** [comment]
This is intentional, as per the spec.  The reason is that a promise for a promise has no practical use case.  A promise represents the **result of an asynchronous operation** so a promise for a promise would make no sense.
