### ISSUE TITLE
can Promise.resolve replace by code like this?

### ISSUE THREAD

**Issue by miracle9312** [then/promise#142]
`Promise.resolve1 = function(value) {
  return new Promise(function(resolve, reject){
    resolve(value);
  })
};`

I have tested 3 cases like value={then:fn}, value=promise,value=''...;but I cannot find any differences between Promise.resolve1 with your Promise.resolve. could you please explain the differences for me. thx!

**Comment by edef1c** [comment]
`Promise.resolve(x)` is intended to behave equivalently to `new Promise((resolve, reject) => resolve(x))`, we've just got a bunch of performance tricks in our version that make use of implementation details.

**Comment by miracle9312** [comment]
thanks,I get it, and your considerations in details inspires me a lot !
