### ISSUE TITLE
who can tell me that what is the meaning of the code?

### ISSUE THREAD

**Issue by navigatorOpera** [then/promise#153]
![image](https://user-images.githubusercontent.com/23136421/56675557-f890ce80-66ee-11e9-8a6c-ed30e520a550.png)

it seems never work

**Comment by ForbesLindesay** [comment]
It is used internally for creating promises that we are going to resolve using internal APIs, rather than the public API. e.g. https://github.com/then/promise/blob/44f6d7aee2b89d0173139d140a4d0d8fe51bb7af/src/core.js#L76

**Comment by navigatorOpera** [comment]
thanks, i get it
