### ISSUE TITLE
promise.race() missing from the API description in README

### ISSUE THREAD

**Issue by debopamsengupta** [then/promise#154]
~~Currently ran into an issue in a project where using this library resulted in errors on Internet Explorer and took me a while to find out that the reason was `Promise.race()` wasn't supported.~~

~~Would be nice to add this method to the library since `Promise.race()` is natively defined in ES6 :)~~

~~Happy to make a PR for this if that's alright !~~

Ignore me ! Just missing in the README :)

**Comment by ForbesLindesay** [comment]
https://github.com/then/promise/blob/master/src/es6-extensions.js#L95-L101

**Comment by debopamsengupta** [comment]
@ForbesLindesay indeed ! I didn't spot `race()` in the documentation in the README and assumed it didn't exist :D 

shall I add it there ?

**Comment by ForbesLindesay** [comment]
That would be good. The proper reference docs are at https://www.promisejs.org/api/

**Comment by debopamsengupta** [comment]
fixed in #155
