### ISSUE TITLE
Questions regarding unhandled rejections

### ISSUE THREAD

**Issue by alamothe** [then/promise#158]
Hello,
I am using this library through React Native. I am capturing unhandled rejections as described here: https://github.com/then/promise#unhandled-rejections. I am doing this in production, so that I can have error logging for my app.

I am a bit puzzled by statements made by the docs.

> Due to the performance cost, you should only do this during development.

Where does the performance cost come from?

> Due to the high probability of false positives, I only recommend using this when debugging specific issues that you think may be being swallowed.

What are these false positives and where do they come from? Can you please give an example?

Thanks!

**Comment by ForbesLindesay** [comment]
False positive:

```js
const promiseThatResolvesSlowly = delay(1000);
const promiseThatRejectsQuickly = Promise.reject('oops');

try {
  await promiseThatResolvesSlowly;
  await promiseThatRejectsQuickly;
} catch (ex) {
  // We handle the rejection here, but it was already reported as an
  // unhandled rejection while we were waiting for promiseThatResolvesSlowly
}
```

The reason it's not recommended in production, is that `promise` must track all unhandled rejections in case they are later resolved and we need to report them as handled. This has a memory overhead and can cause a memory leak in applications that deliberately ignore some rejected promises.

**Comment by alamothe** [comment]
Thanks for the explanation!

You probably meant for that to run in parallel?
```typescript
const promiseThatResolvesSlowly = delay(1000);
const promiseThatRejectsQuickly = Promise.reject('oops');

try {
  await Promise.all([
    promiseThatResolvesSlowly, 
    promiseThatRejectsQuickly,
  ]);
} catch (ex) {
  // We handle the rejection here, but it was already reported as an
  // unhandled rejection while we were waiting for promiseThatResolvesSlowly
}
```

I think I'm starting to understand the problem better now, after a year of React experience 😄 

I'm wondering why the best practices here are not popularized more, instead of just being hinted at in this obscure issue: https://github.com/facebook/react-native/issues/2585

**Comment by alamothe** [comment]
...my bad, your example is correct, mine isn't (`Promise.all` only waits for first rejection)

**Comment by ForbesLindesay** [comment]
@alamothe more importantly, `Promise.all` would mark the rejection as handled whenever it happens. so even if you had multiple rejections, all with different delays, they would all be marked as handled. Only the first would actually be re-thrown into the try/catch block though.
