### ISSUE TITLE
code refactor. use new.target to detect if promise is called with new instead of this check

### ISSUE THREAD

**Issue by sktguha** [then/promise#165]
In https://github.com/then/promise/blob/91b7b4cb6ad0cacc1c70560677458fe0aac2fa67/src/core.js#L55
for checking whether the promise constructor is called with new it is better to use new target
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target
if it is accepted the change then I can make a PR for this

**Comment by ForbesLindesay** [comment]
This does not seem to be worth working on, given that the current approach works.

**Comment by sktguha** [comment]
Alright sure
