### ISSUE TITLE
It's difference between native and shim

### ISSUE THREAD

**Issue by ahnuchen** [then/promise#168]
When I run the following code in browser（chrome v66） that support promise native

```javascript
let promiseA = new Promise(resolve => resolve('A'))
let promiseB = new Promise(resolve => resolve(promiseA))
let promiseC = new Promise(resolve => resolve('C'))

promiseB.then(arg => console.log(arg));
promiseC.then(arg => console.log(arg));
```

the result is `C A`

but when I run the same code with es6-promise，the result is reverse: `A C`
which one is right?

**Comment by edef1c** [comment]
Both are correct — callback order is unspecified.
