### ISSUE TITLE
[BUG]Why this promise execute queue is not same with v8 Promise。

### ISSUE THREAD

**Issue by jjkbb123** [then/promise#175]
example
```
Promise.resolve()
  .then(_ => {
    console.log(0)
    return Promise.resolve()
  })
  .then(_ => {
    console.log(1)
  })

Promise.resolve()
  .then(_ => {Ï
    console.log(3)
  })
  .then(_ => {
    console.log(4)
  })
  .then(_ => {
    console.log(5)
  })
  .then(_ => {
    console.log(6)
  })
```
v8 Promise: 0 3 4 5 1 6
this Promise: 0 3 1 4 5 6

**Comment by edef1c** [comment]
Neither the execution ordering of Chrome/V8 Promise callbacks, nor that of then/promise, are defined, documented, or stable guarantees. It is simply undefined, and even it being stable for a given version of the Promise implementation ought not to be relied on.
