### ISSUE TITLE
event loop starving with promise 4.0

### ISSUE THREAD

**Issue by jeromew** [then/promise#29]
Hello,
I upgraded to promise 4.0. This new version (with node.js) uses `asap`to async the resolution instead of the previous next-tick.js.
- asap => nextTick
- next-tick.js => setImmediate

I hit a problem of a starving event loop leading to the asap(task) never called in my server, in relation to node-sqlite3.

you can check https://github.com/mapbox/node-sqlite3/pull/184#issuecomment-34969734 for more information on where this comes from.

The problem does not appear when using setImmediate (reverting to promise 3.2).

I am trying to gather information as to how the problem should be fixed. Any idea will be welcome.

**Comment by ForbesLindesay** [comment]
@vvo It **shouldn't** be a problem memory wise, but in practice it might be.  See #67 for extended discussion on this topic.
