### ISSUE TITLE
Have denodeify() support multiple response parameters?

### ISSUE THREAD

**Issue by voxpelli** [then/promise#47]
I was currently about to wrap the [request](https://github.com/mikeal/request) module with `denodeify()`, but the `request()` returns two parameters in its response and `denodeify()` only forwards the first parameter – therefore it doesn't work.

Is there a reason for `denodeify()` to only return the first parameter? I think it could resolve the promise with them all in array if it finds that there are more than one response parameter.

That would make these two equal:

``` javascript
function callback (err, param1, param2) {
};
```

``` javascript
denodeify().then(function (result) {
  var param1 = result[0]
    , param2 = result[1];
});
```

**Comment by louwers** [comment]
is this already possible with some library?

**Comment by ForbesLindesay** [comment]
Some libraries (e.g. Q) fall back to returning an array if there are extra arguments.

**Comment by louwers** [comment]
I was not aware of that! Thank you.

Now I am using the [denodify](https://www.npmjs.com/package/denodeify), package, which gives you even more customization settings on how to deal with multiple parameters.
