### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by lukeapage** [then/promise#57]
I can't find a changelog and I don't know if I should worry about changes from v5 to v6 since you upped the major version?

**Comment by denis-sokolov** [comment]
Now you bumped to v7 and it's again very unclear what's the breakage.
[Diff](https://github.com/then/promise/compare/6.1.0...7.0.0) helps a tiny bit, but I really can't understand the scope of all changes without diving into the internals of the library.
Above mentioned [releases page](https://github.com/then/promise/releases) has no information either.
A simple `CHANGELOG.md` in the root of the project with a short list of things that have been broken in a major version would really help.
Thanks!

**Comment by charlesgreen** [comment]
Really wish there was a change log as well or an up to date releases page with breaking changes. Great software but it makes it very difficult to use.
