### ISSUE TITLE
Missing Promise.reject in the documentation

### ISSUE THREAD

**Issue by BorisKozo** [then/promise#68]
Maybe some other stuff is missing?
Had to dig in the code to make sure it exists.

Would you accept a PR with a fix?

**Comment by nathan7** [comment]
I'm aware that the docs are somewhat lacking, so doc PRs are always welcome! (and get you internet points for being awesome)

**Comment by ForbesLindesay** [comment]
Yes please, that would be awesome.

**Comment by BorisKozo** [comment]
What is the relation between the node.js version and the browser version? It seems that there is a version 4.0.0 (in the readme) and a version 6.0.1 on the website. Which is the correct link?

**Comment by ForbesLindesay** [comment]
I'm just not always very good at updating the readme when I update the website.  The website is a somewhat separate project that just happens to host a copy of this library (and is also maintained by me).

**Comment by nathan7** [comment]
Promise.reject seems to be documented now, closing.
