### ISSUE TITLE
Switch to asap/raw for everything but Promise#done

### ISSUE THREAD

**Issue by nathan7** [then/promise#74]
See discussion in #61

**Comment by ForbesLindesay** [comment]
Implemented in #73.  The only issue is we lose support for domains.  I'm not sure if that matters though tbh.

**Comment by nathan7** [comment]
Do domains matter anywhere but in .done? I'm not quite sure.

**Comment by ForbesLindesay** [comment]
Yes, in as much as you have to maintain the domain at every step of the way in order for it to work.  The other thing is that you can use the domains to store data, and do other crazy hacky things.  Not sure if any of them are good ideas we should be trying to support, but none of them work unless we support domains all the way through.
