### ISSUE TITLE
Default THEN?

### ISSUE THREAD

**Issue by vitaly-t** [then/promise#76]
It's more of a question, because I don't quite understand the logic of the code below:
```javascript
promise.resolve()
    .then(function () {
        console.log('then-1');
    })
    .then(function () {
        console.log('then-2');
    })
    .then(function () {
        console.log('then-3');
    });
```
produces the following output:
```javascript
then-1
then-2
then-3
```
as opposed to:
```javascript
then-1
```

I mean, we do not resolve anything pass the first `then` function, so why do we still get into every `then` that follows? Please explain, 'cos I feel dumb right now :)

**Comment by nathan7** [comment]
`then` uses the return value, which is `undefined` here. All of the promises are resolved with `undefined`.
