### ISSUE TITLE
Promise.all doesn't support multiple arguments

### ISSUE THREAD

**Issue by rhgb** [then/promise#77]
The usage in document
```javascript
Promise.all(Promise.resolve('a'), 'b', Promise.resolve('c'))
  .then(function (res) {
    assert(res[0] === 'a')
    assert(res[1] === 'b')
    assert(res[2] === 'c')
  })
```
is actually not supported, according to source code of `/lib/es6-extensions.js`.
As ES6 only support `Promise.all(iterable)` usage, maybe it's README file which should be updated.

**Comment by vitaly-t** [comment]
Method `all` expects only one parameter - an array or an iterable object. It was never meant to support multiple parameters.

See also: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

**Comment by rhgb** [comment]
I found the README has been corrected so this issue can be closed. Thanks
