### ISSUE TITLE
needed shim, IE8 support

### ISSUE THREAD

**Issue by vvo** [then/promise#79]
I love then/promise and wants to use it in a JavaScript REST API client I am working on.

I need to support IE8 and was wondering what parts of es5-shim were really needed for then/promise?

Do you think we could make it old-browsers compatible with IE8 with little changes? Thanks

**Comment by vvo** [comment]
@ForbesLindesay updated the issue to be more specific

**Comment by ForbesLindesay** [comment]
It depends on exactly what you need `require('promise/lib/core')` just requires `Function.prototype.bind` to be polyfilled.  If you want to use `Promise.race` from `require('promise/lib/es6-extensions')` you need to polyfill `Array.prototype.forEach`.  I believe thats everything.  This list may change slightly over time though.

**Comment by vvo** [comment]
Thanks, I ended up using https://github.com/jakearchibald/es6-promise/ which is IE8 compatible.
