### ISSUE TITLE
denodeify runs with undefined this

### ISSUE THREAD

**Issue by brainsiq** [then/promise#94]
```
var O = function() {
  this.test = 'hi';
};

O.prototype.aFunction = function() {
  this.test = 'bye';
};

var o = new O();
Promise.denodeify(o.aFunction)();
```

The promise fails with `this` being undefined. It does work however using `call` and specifying `this` yourself: 

```
Promise.denodeify(o.aFunction).call(o);
```

To my knowledge there wouldn't be a way of working out what `this` is supposed to be but maybe the API could be a bit nicer by accepting an optional parameter that would be used as `this`. 

```
Promise.denodeify(o, o.aFunction)();
```

Happy to submit a pull req with a fix if you agree with the proposed solution. Otherwise it'd good to update the docs to point out this potential issue as it'll probably catch out a lot of people using this to wrap third party functions.

**Comment by ForbesLindesay** [comment]
We support these APIs via JavaScripts built in:

```js
Promise.denodeify(o.aFunction.bind(o))();
```
