### ISSUE TITLE
conditional execution of promises

### ISSUE THREAD

**Issue by colmsjo** [then/promise#96]
I'd like to understand how conditional execution of promises is handled best.

I ended up developing these helpers but perhaps there is a better way??
https://github.com/colmsjo/promise-ifandor

Any suggestions are greatly appreciated!

**Comment by ForbesLindesay** [comment]
I've submitted a pull request to that to try and tidy up the code.  It does change some semantics though, as I'm not entirely sure what the intended semantics were in a lot of cases.

To clear something up:

A promise is never executed.  A promise is a representation of the result of an asynchronous operation.  The asynchronous operation (typically represented by a function that returns a promise) is executed, but the Promise is not executed.  It is inert/imutable.

By "conditional execution of promises" do you mean things like:

"If p1 is eventually fulfilled with true, do X, else do Y"

or do you mean:

"The same function should work whether it's arguments are values of promises"

**Comment by colmsjo** [comment]
Yes, it async operations, sorry if the vocabulary isn't correct (I'm new to this).

I want promiseIf(b, p)  to achieve: 
"if b is true (or if b is a promise that resolves to true) then return p otherwise return a promise that will resolve to null"

and I want promiseAnd(p1, p2) to achieve:
"if p1 is true (or if p1 is a promise that resolves to true) then return a promise with the value that p2 resolves to"

promiseOr and promiseNot are analog.

Thank's for the quick reply!

**Comment by colmsjo** [comment]
Ok, I checked the pull request. This is much cleaner. Thank's!!

**Comment by colmsjo** [comment]
I've rewritten the function is order to make promiseAnd & promiseOr to behave like the && and || operators. The second argument is now only resolved when required. I'd had to re-write the deferred function also in order to defer the execution of functions provided.

It would be great to have the functions in this library. If you don't want to include them, perhaps you can mention my library in the README. This way we'll be able to attract more developers and prove the functions (or find alternative solutions).

Thank's!

**Comment by ForbesLindesay** [comment]
One key issue I think your missing is that `Promise.resolve(p)` does not mean "Resolve p" but instead it means, "Create a new Promise and resolve it with p".

It is the responsibility of the code that creates the promise (using `new Promise(function (resolve, reject) { /*...*/ })`) to decide whether/when to resolve the promise.  The consumer **cannot** influence that process.

Put another way, Promises are not lazy.  They begin generating their value as soon as they are created, when you wait for them is irrelevant.

If you prefer an example, the following code logs approximately "2000".  The body of the promise starts executing straight away, so when we ask for its value, 2 seconds later, it is already ready.

```js
var start = Date.now();
var p = new Promise(function (resolve) {
  setTimeout(function () { resolve('foo'); }, 2000);
});
setTimeout(function () {
  p.then(function (res) {
    assert(res === 'foo');
    var end = Date.now();
    console.log(end - start);
  });
}, 2000);
```

**Comment by colmsjo** [comment]
Yes, I realized that Promises aren't lazy. This is why I changed my deferred function postpone the evaluation. I also enhanced it once more (just now) to take a `this` argument.

This is the new version.
```
// takes the arguments: func, this, funcArg1, ..., funcArgN
exports.deferred = function() {
  var args = Array.prototype.slice.call(arguments);
  var f = args.shift();
  if (typeof f === 'function' && !f.then) {
    var self = args.shift();
    return {
      then: function(x) {return Promise.resolve(f.apply(self, args)).then(x);}
    }
  }
  else return Promise.resolve(f);
};
```

Now, this will not print a message:
`> P.promiseAnd(false, P.deferred(console.log, this, 'hi there')).then()`

but this will:
`> P.promiseAnd(true, P.deferred(console.log, this, 'hi there')).then()`

**Comment by colmsjo** [comment]
Ok, I tested with your version of promiseAnd and it behaves the same way. I'll use this version instead. This really requires attention to the details...

Thank's again.

**Comment by ForbesLindesay** [comment]
What you're looking for is called a LazyPromise.  You can see an implementation at https://github.com/then/lazy-promise which manages to fix a few design pitfalls that your implementation has.

I strongly encourage you to use that instead.

**Comment by colmsjo** [comment]
Ok, I'll check this out

**Comment by ForbesLindesay** [comment]
To be specific:

`.when` should probably support an `onRejected` as well as `onFulfilled` to be passed to `.then`.  It should accept either handler being absent.  This would then match the API of many other libraries:

```js
exports.when = function(promise, onFulfilled, onRejected) {
  return Promise.resolve(promise).then(onFulfilled, onRejected);
};
```

Deferred is trying to do a million things at once.  Why not just have:

```js
exports.deferred = function (fn) {
  return new LazyPromise(function (resolve, reject) {
    resolve(fn);
  });
};
```

The advantage to this is that people are less likely to assume that `exports.deferred(foo())` magically makes `foo` lazy.  That would correctly handle both synchronous and asynchronous errors.  Then instead of calling `exports.deferred(console.log, console, 'foo')` you call `exports.deferred(console.log.bind(console, 'foo'))` which I think is much clearer since it makes more use of built in methods.

`promiseIf` and `promiseAnd` are so similar, does it make sense to have both?

Does `promiseNot` provide any real value?

As a final thing to consider, laziness is only local.  It does not propagate, so:

```js
function foo() {
  return new LazyPromise(function (resolve) {
    resolve(triggerSideEffect());
  });
}
function bar() {
  return foo().then(function () {});
}
promiseAnd(false, foo()); // does not trigger side effect because the promise returned by `foo` is never "thened"
promiseAnd(false, bar()); // does trigger side effect because the promise returned by `foo` is "thened" as soon as you call `bar`.
```

**Comment by colmsjo** [comment]
I used this approach but `deferred` don't behave like intended, and I just cannot understand why:

```
$ node
> var LazyPromise = require('lazy-promise');
undefined
> var deferred = function (fn) {
...   return new LazyPromise(function (resolve, reject) {
.....     resolve(fn);
.....   });
... };
undefined
> LazyPromise(function(f,r){ f(console.log('foo')) } );
{ then: [Function] }
> LazyPromise(function(f,r){ f(console.log('foo')) } ).then();
{ then: [Function] }
> foo

undefined
> deferred(function(){ console.log('foo') });
{ then: [Function] }
> deferred(function(){ console.log('foo') }).then();
{ then: [Function] }
>
```

Why does not  `deferred(function(){ console.log('foo') }).then();` print `foo` like expected?

**Comment by ForbesLindesay** [comment]
Replace resolve(fn) with resolve(fn())

**Comment by colmsjo** [comment]
ok, now it works. Is the reason that `resolve` doesn't invoke functions (in the same way as `then`)?

**Comment by ForbesLindesay** [comment]
Yes.  You can resolve a promise with a function.  I'd suggest https://www.promisejs.org/ as general introductory reading on what promises are and what purpose they serve.  I'd love to get your take on which bits are hard to understand.
